language: python
python:
  - 2.7
  - 3.3

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - nosetests test_tweetvac.py 
